services:
  db:
    image: postgres:16.1
    volumes:
      - empath-db-data-local:/var/lib/postgresql/data/
    container_name: empath-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - backend

  s3:
    image: minio/minio
    container_name: empath-s3
    volumes:
      - empath-s3-data-local:/data
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${S3_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${S3_ROOT_PASSWORD}
    ports:
      - ${S3_PORT}:9000
      - ${S3_PORT_GUI}:9001 
    command: server /data --console-address ":9001"
    networks:
      - backend

  redis:
    container_name: empath-redis
    image: redis:7-alpine
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend

  backend:
    container_name: empath-backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    image: empath-backend
    volumes:
      - .:/backend #in container folder
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: postgres-db
    entrypoint: ["/backend/docker/app.sh"]
    networks:
      - backend



networks:
  backend:
    driver: bridge

volumes:
  empath-db-data-local:
  empath-s3-data-local:

