"""make tag name unique

Revision ID: a0f1f9c8a3ef
Revises: 2ca9dd8629f8
Create Date: 2025-03-16 17:38:06.887636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f1f9c8a3ef'
down_revision: Union[str, None] = '2ca9dd8629f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_tag_name'), 'tag', ['name'], schema='article')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_tag_name'), 'tag', schema='article', type_='unique')
    # ### end Alembic commands ###
