"""cv & vacancy rel  

Revision ID: 79d2da51c229
Revises: aa8ece152761
Create Date: 2025-04-07 14:15:39.234463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d2da51c229'
down_revision: Union[str, None] = 'aa8ece152761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rel_cv_vacancy',
    sa.Column('cv_id', sa.Uuid(), nullable=False),
    sa.Column('vacancy_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['job.cv.id'], name=op.f('fk_rel_cv_vacancy_cv_id_cv'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['job.vacancy.id'], name=op.f('fk_rel_cv_vacancy_vacancy_id_vacancy'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cv_id', 'vacancy_id', name=op.f('pk_rel_cv_vacancy')),
    schema='job'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rel_cv_vacancy', schema='job')
    # ### end Alembic commands ###
