"""add rating to user profile

Revision ID: 01ed8846430e
Revises: 601046233d38
Create Date: 2025-04-15 19:11:00.116710

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01ed8846430e"
down_revision: str | None = "601046233d38"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("rating", sa.BigInteger(), server_default="0", nullable=False),
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "rating", schema="auth")
    # ### end Alembic commands ###
