"""add likes dislikes views for article

Revision ID: 601046233d38
Revises: 0fb9d84960d2
Create Date: 2025-04-15 17:11:00.720481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601046233d38'
down_revision: Union[str, None] = '0fb9d84960d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rel_article_user_dislike',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.article.id'], name=op.f('fk_rel_article_user_dislike_article_id_article'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_rel_article_user_dislike_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'user_id', name=op.f('pk_rel_article_user_dislike')),
    schema='article'
    )
    op.create_table('rel_article_user_like',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.article.id'], name=op.f('fk_rel_article_user_like_article_id_article'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_rel_article_user_like_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'user_id', name=op.f('pk_rel_article_user_like')),
    schema='article'
    )
    op.create_table('rel_article_user_view',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.article.id'], name=op.f('fk_rel_article_user_view_article_id_article'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_rel_article_user_view_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'user_id', name=op.f('pk_rel_article_user_view')),
    schema='article'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rel_article_user_view', schema='article')
    op.drop_table('rel_article_user_like', schema='article')
    op.drop_table('rel_article_user_dislike', schema='article')
    # ### end Alembic commands ###
