"""add status field for cv vacancy rel 

Revision ID: 8a1ce711e9c7
Revises: 79d2da51c229
Create Date: 2025-04-07 16:44:47.571778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1ce711e9c7'
down_revision: Union[str, None] = '79d2da51c229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rel_cv_vacancy', sa.Column('status', sa.String(length=50), server_default='pending', nullable=False), schema='job')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rel_cv_vacancy', 'status', schema='job')
    # ### end Alembic commands ###
