"""retype work format

Revision ID: ec98ddc59c92
Revises: 7840a916e484
Create Date: 2025-04-05 08:52:02.964655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec98ddc59c92'
down_revision: Union[str, None] = '7840a916e484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_format', 'name',
               existing_type=postgresql.ENUM('REMOTE', 'ONSITE', 'HYBRID', name='workformatenum'),
               type_=sa.String(),
               existing_nullable=False,
               schema='job')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_format', 'name',
               existing_type=sa.String(),
               type_=postgresql.ENUM('REMOTE', 'ONSITE', 'HYBRID', name='workformatenum'),
               existing_nullable=False,
               schema='job')
    # ### end Alembic commands ###
