"""empty message

Revision ID: 4d43e1aa014a
Revises:
Create Date: 2025-01-12 19:34:22.492803

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d43e1aa014a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA auth")
    op.create_table(
        "user",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("password", sa.LargeBinary(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("nickname", sa.String(length=20), nullable=True),
        sa.Column(
            "gender", sa.Enum("male", "female", "other", name="gender"), nullable=True
        ),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("lastname", sa.String(length=255), nullable=True),
        sa.Column("patronymic", sa.String(length=255), nullable=True),
        sa.Column("date_birth", sa.Date(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.String(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_user_email"), "user", ["email"], unique=True, schema="auth"
    )
    op.create_index(
        op.f("ix_auth_user_id"), "user", ["id"], unique=False, schema="auth"
    )
    op.create_table(
        "refresh_token",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.String(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.user.id"],
            name=op.f("fk_refresh_token_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_token")),
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_refresh_token_id"),
        "refresh_token",
        ["id"],
        unique=False,
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_auth_refresh_token_id"), table_name="refresh_token", schema="auth"
    )
    op.drop_table("refresh_token", schema="auth")
    op.drop_index(op.f("ix_auth_user_id"), table_name="user", schema="auth")
    op.drop_index(op.f("ix_auth_user_email"), table_name="user", schema="auth")
    op.drop_table("user", schema="auth")
    op.execute("DROP SCHEMA auth")
    # ### end Alembic commands ###
