"""add specialization for article

Revision ID: 0fb9d84960d2
Revises: 9eb9e30b1539
Create Date: 2025-04-14 14:28:46.296132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb9d84960d2'
down_revision: Union[str, None] = '9eb9e30b1539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialization',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialization')),
    sa.UniqueConstraint('name', name=op.f('uq_specialization_name')),
    schema='article'
    )
    op.create_index(op.f('ix_article_specialization_id'), 'specialization', ['id'], unique=False, schema='article')
    op.add_column('article', sa.Column('specialization_id', sa.Uuid(), nullable=True), schema='article')
    op.create_foreign_key(op.f('fk_article_specialization_id_specialization'), 'article', 'specialization', ['specialization_id'], ['id'], source_schema='article', referent_schema='article', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_article_specialization_id_specialization'), 'article', schema='article', type_='foreignkey')
    op.drop_column('article', 'specialization_id', schema='article')
    op.drop_index(op.f('ix_article_specialization_id'), table_name='specialization', schema='article')
    op.drop_table('specialization', schema='article')
    # ### end Alembic commands ###
