"""add rel comment and user like dislikes 

Revision ID: b1f6143cb542
Revises: a4c4f0400a3d
Create Date: 2025-04-18 19:35:53.754138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f6143cb542'
down_revision: Union[str, None] = 'a4c4f0400a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rel_comment_user_dislike',
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['article.comment.id'], name=op.f('fk_rel_comment_user_dislike_comment_id_comment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_rel_comment_user_dislike_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', 'user_id', name=op.f('pk_rel_comment_user_dislike')),
    schema='article'
    )
    op.create_table('rel_comment_user_like',
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['article.comment.id'], name=op.f('fk_rel_comment_user_like_comment_id_comment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_rel_comment_user_like_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', 'user_id', name=op.f('pk_rel_comment_user_like')),
    schema='article'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rel_comment_user_like', schema='article')
    op.drop_table('rel_comment_user_dislike', schema='article')
    # ### end Alembic commands ###
