"""Recruitment vacancy add field

Revision ID: ce5c278e42bc
Revises: 00f7d5b4f5a8
Create Date: 2025-04-01 17:53:41.039785

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce5c278e42bc"
down_revision: str | None = "00f7d5b4f5a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vacancy",
        sa.Column("responsibility", sa.String(), nullable=False),
        schema="job",
    )
    op.add_column(
        "vacancy",
        sa.Column("requirements", sa.String(), nullable=False),
        schema="job",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacancy", "requirements", schema="job")
    op.drop_column("vacancy", "responsibility", schema="job")
    # ### end Alembic commands ###
