"""alter_article

Revision ID: 2ca9dd8629f8
Revises: 372360d9cf8a
Create Date: 2025-03-13 22:32:13.587694

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ca9dd8629f8"
down_revision: Union[str, None] = "372360d9cf8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("article", "title", existing_type=sa.VARCHAR(length=50), nullable=False, schema="article")
    op.alter_column("article", "text", existing_type=sa.TEXT(), nullable=False, schema="article")
    op.alter_column("article", "is_visible", existing_type=sa.BOOLEAN(), nullable=False, schema="article")
    op.alter_column("article", "author_id", existing_type=sa.UUID(), nullable=False, schema="article")
    op.alter_column("article", "views_cnt", existing_type=sa.BIGINT(), nullable=False, schema="article")
    op.alter_column("article", "likes_cnt", existing_type=sa.BIGINT(), nullable=False, schema="article")
    op.alter_column("article", "dislikes_cnt", existing_type=sa.BIGINT(), nullable=False, schema="article")
    op.alter_column("article_img", "url", existing_type=sa.TEXT(), nullable=False, schema="article")
    op.alter_column("article_img", "article_id", existing_type=sa.UUID(), nullable=False, schema="article")
    op.alter_column("sub_article", "article_id", existing_type=sa.UUID(), nullable=False, schema="article")
    op.alter_column("sub_article", "title", existing_type=sa.VARCHAR(length=50), nullable=False, schema="article")
    op.alter_column("sub_article", "text", existing_type=sa.TEXT(), nullable=False, schema="article")
    op.alter_column("sub_article_img", "url", existing_type=sa.TEXT(), nullable=False, schema="article")
    op.alter_column("sub_article_img", "sub_article_id", existing_type=sa.UUID(), nullable=False, schema="article")
    op.alter_column("tag", "name", existing_type=sa.VARCHAR(length=50), nullable=False, schema="article")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tag", "name", existing_type=sa.VARCHAR(length=50), nullable=True, schema="article")
    op.alter_column("sub_article_img", "sub_article_id", existing_type=sa.UUID(), nullable=True, schema="article")
    op.alter_column("sub_article_img", "url", existing_type=sa.TEXT(), nullable=True, schema="article")
    op.alter_column("sub_article", "text", existing_type=sa.TEXT(), nullable=True, schema="article")
    op.alter_column("sub_article", "title", existing_type=sa.VARCHAR(length=50), nullable=True, schema="article")
    op.alter_column("sub_article", "article_id", existing_type=sa.UUID(), nullable=True, schema="article")
    op.alter_column("article_img", "article_id", existing_type=sa.UUID(), nullable=True, schema="article")
    op.alter_column("article_img", "url", existing_type=sa.TEXT(), nullable=True, schema="article")
    op.alter_column("article", "dislikes_cnt", existing_type=sa.BIGINT(), nullable=True, schema="article")
    op.alter_column("article", "likes_cnt", existing_type=sa.BIGINT(), nullable=True, schema="article")
    op.alter_column("article", "views_cnt", existing_type=sa.BIGINT(), nullable=True, schema="article")
    op.alter_column("article", "author_id", existing_type=sa.UUID(), nullable=True, schema="article")
    op.alter_column("article", "is_visible", existing_type=sa.BOOLEAN(), nullable=True, schema="article")
    op.alter_column("article", "text", existing_type=sa.TEXT(), nullable=True, schema="article")
    op.alter_column("article", "title", existing_type=sa.VARCHAR(length=50), nullable=True, schema="article")
    # ### end Alembic commands ###
