"""add is relevant field for work exp

Revision ID: b6c2a6cacde3
Revises: 1e158284f081
Create Date: 2025-04-05 12:12:06.648540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c2a6cacde3'
down_revision: Union[str, None] = '1e158284f081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_exp', sa.Column('is_relevant', sa.Boolean(), nullable=False), schema='job')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_exp', 'is_relevant', schema='job')
    # ### end Alembic commands ###
