"""change article title len

Revision ID: 237960a35635
Revises: b6c2a6cacde3
Create Date: 2025-04-05 14:05:52.377673

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "237960a35635"
down_revision: Union[str, None] = "b6c2a6cacde3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "article",
        "title",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=500),
        existing_nullable=False,
        schema="article",
    )
    op.alter_column(
        "sub_article",
        "title",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=500),
        existing_nullable=False,
        schema="article",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sub_article",
        "title",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        schema="article",
    )
    op.alter_column(
        "article",
        "title",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        schema="article",
    )
    # ### end Alembic commands ###
