"""add author_id to comment

Revision ID: 06aa72dbd11d
Revises: 24720dcd8624
Create Date: 2025-03-29 16:20:32.579426

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06aa72dbd11d"
down_revision: Union[str, None] = "24720dcd8624"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comment", sa.Column("author_id", sa.Uuid(), nullable=False), schema="article")
    op.create_foreign_key(
        op.f("fk_comment_author_id_user"),
        "comment",
        "user",
        ["author_id"],
        ["id"],
        source_schema="article",
        referent_schema="auth",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_comment_author_id_user"), "comment", schema="article", type_="foreignkey")
    op.drop_column("comment", "author_id", schema="article")
    # ### end Alembic commands ###
