"""remove cv_id pk

Revision ID: 9eb9e30b1539
Revises: 8a1ce711e9c7
Create Date: 2025-04-09 07:16:20.972822

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9eb9e30b1539"
down_revision: str | None = "8a1ce711e9c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("pk_work_exp", "work_exp", type_="primary", schema="job")
    op.create_primary_key("pk_work_exp", "work_exp", ["id"], schema="job")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("pk_work_exp", "work_exp", type_="primary", schema="job")
    op.create_primary_key("pk_work_exp", "work_exp", ["id", "cv_id"], schema="job")
    # ### end Alembic commands ###
