"""Recruitment remove fields skills

Revision ID: d32bc3d6b942
Revises: ce5c278e42bc
Create Date: 2025-04-01 18:08:16.696924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32bc3d6b942'
down_revision: Union[str, None] = 'ce5c278e42bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'responsibility', schema='job')
    op.drop_column('skill', 'requirement', schema='job')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('requirement', sa.VARCHAR(), autoincrement=False, nullable=False), schema='job')
    op.add_column('skill', sa.Column('responsibility', sa.VARCHAR(), autoincrement=False, nullable=False), schema='job')
    # ### end Alembic commands ###
