"""Recruitment upgrade salary 

Revision ID: 7741741c6e55
Revises: d32bc3d6b942
Create Date: 2025-04-01 18:13:02.968781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7741741c6e55'
down_revision: Union[str, None] = 'd32bc3d6b942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancy', 'salary_from',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               schema='job')
    op.alter_column('vacancy', 'salary_to',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True,
               schema='job')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancy', 'salary_to',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='job')
    op.alter_column('vacancy', 'salary_from',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='job')
    # ### end Alembic commands ###
