"""make skill unique 

Revision ID: aa8ece152761
Revises: 237960a35635
Create Date: 2025-04-07 14:03:07.902180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8ece152761'
down_revision: Union[str, None] = '237960a35635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_skill_name'), 'skill', ['name'], schema='job')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_skill_name'), 'skill', schema='job', type_='unique')
    # ### end Alembic commands ###
