"""add cv file field 

Revision ID: 1e158284f081
Revises: b686c723ab5d
Create Date: 2025-04-05 09:25:19.579969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e158284f081'
down_revision: Union[str, None] = 'b686c723ab5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv', sa.Column('cv_file', sa.String(), nullable=True), schema='job')
    op.add_column('work_exp', sa.Column('start_date', sa.Date(), nullable=False), schema='job')
    op.add_column('work_exp', sa.Column('end_date', sa.Date(), nullable=True), schema='job')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_exp', 'end_date', schema='job')
    op.drop_column('work_exp', 'start_date', schema='job')
    op.drop_column('cv', 'cv_file', schema='job')
    # ### end Alembic commands ###
