"""cv tables

Revision ID: b686c723ab5d
Revises: 2bd7b266dc3c
Create Date: 2025-04-05 09:14:57.129062

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b686c723ab5d"
down_revision: Union[str, None] = "2bd7b266dc3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cv",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("salary_from", sa.BigInteger(), nullable=True),
        sa.Column("salary_to", sa.BigInteger(), nullable=True),
        sa.Column(
            "education",
            sa.Enum("SCHOOL", "BACHELOR", "MASTER", "DOCTORATE", name="educationenum", native_enum=False, length=50),
            nullable=False,
        ),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("about_me", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["auth.user.id"], name=op.f("fk_cv_author_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cv")),
        schema="job",
    )
    op.create_index(op.f("ix_job_cv_id"), "cv", ["id"], unique=False, schema="job")
    op.create_table(
        "rel_cv_additional_skill",
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("cv_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["cv_id"], ["job.cv.id"], name=op.f("fk_rel_cv_additional_skill_cv_id_cv"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["job.skill.id"], name=op.f("fk_rel_cv_additional_skill_skill_id_skill"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("skill_id", "cv_id", name=op.f("pk_rel_cv_additional_skill")),
        schema="job",
    )
    op.create_table(
        "rel_cv_employment_type",
        sa.Column("employment_type_id", sa.Uuid(), nullable=False),
        sa.Column("cv_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["cv_id"], ["job.cv.id"], name=op.f("fk_rel_cv_employment_type_cv_id_cv"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["employment_type_id"],
            ["job.employment_type.id"],
            name=op.f("fk_rel_cv_employment_type_employment_type_id_employment_type"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("employment_type_id", "cv_id", name=op.f("pk_rel_cv_employment_type")),
        schema="job",
    )
    op.create_table(
        "rel_cv_skill",
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("cv_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["cv_id"], ["job.cv.id"], name=op.f("fk_rel_cv_skill_cv_id_cv"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["job.skill.id"], name=op.f("fk_rel_cv_skill_skill_id_skill"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("skill_id", "cv_id", name=op.f("pk_rel_cv_skill")),
        schema="job",
    )
    op.create_table(
        "rel_cv_work_format",
        sa.Column("work_format_id", sa.Uuid(), nullable=False),
        sa.Column("cv_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["cv_id"], ["job.cv.id"], name=op.f("fk_rel_cv_work_format_cv_id_cv"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["work_format_id"],
            ["job.work_format.id"],
            name=op.f("fk_rel_cv_work_format_work_format_id_work_format"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("work_format_id", "cv_id", name=op.f("pk_rel_cv_work_format")),
        schema="job",
    )
    op.create_table(
        "rel_cv_work_schedule",
        sa.Column("work_schedule_id", sa.Uuid(), nullable=False),
        sa.Column("cv_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["cv_id"], ["job.cv.id"], name=op.f("fk_rel_cv_work_schedule_cv_id_cv"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["work_schedule_id"],
            ["job.work_schedule.id"],
            name=op.f("fk_rel_cv_work_schedule_work_schedule_id_work_schedule"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("work_schedule_id", "cv_id", name=op.f("pk_rel_cv_work_schedule")),
        schema="job",
    )
    op.create_table(
        "work_exp",
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("cv_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["cv_id"], ["job.cv.id"], name=op.f("fk_work_exp_cv_id_cv"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("cv_id", "id", name=op.f("pk_work_exp")),
        schema="job",
    )
    op.create_index(op.f("ix_job_work_exp_id"), "work_exp", ["id"], unique=False, schema="job")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_work_exp_id"), table_name="work_exp", schema="job")
    op.drop_table("work_exp", schema="job")
    op.drop_table("rel_cv_work_schedule", schema="job")
    op.drop_table("rel_cv_work_format", schema="job")
    op.drop_table("rel_cv_skill", schema="job")
    op.drop_table("rel_cv_employment_type", schema="job")
    op.drop_table("rel_cv_additional_skill", schema="job")
    op.drop_index(op.f("ix_job_cv_id"), table_name="cv", schema="job")
    op.drop_table("cv", schema="job")
    # ### end Alembic commands ###
