"""add recruiter model

Revision ID: 90c6732549c2
Revises: 7741741c6e55
Create Date: 2025-04-03 18:32:08.489017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c6732549c2'
down_revision: Union[str, None] = '7741741c6e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiter',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('about_us', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['auth.user.id'], name=op.f('fk_recruiter_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recruiter')),
    schema='job'
    )
    op.create_index(op.f('ix_job_skill_id'), 'skill', ['id'], unique=False, schema='job')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_skill_id'), table_name='skill', schema='job')
    op.drop_table('recruiter', schema='job')
    # ### end Alembic commands ###
