"""add parent id and is visible comment  

Revision ID: a4c4f0400a3d
Revises: 01ed8846430e
Create Date: 2025-04-18 19:10:05.344951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c4f0400a3d'
down_revision: Union[str, None] = '01ed8846430e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_id', sa.Uuid(), nullable=True), schema='article')
    op.add_column('comment', sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False), schema='article')
    op.create_foreign_key(op.f('fk_comment_parent_id_comment'), 'comment', 'comment', ['parent_id'], ['id'], source_schema='article', referent_schema='article', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_comment_parent_id_comment'), 'comment', schema='article', type_='foreignkey')
    op.drop_column('comment', 'is_visible', schema='article')
    op.drop_column('comment', 'parent_id', schema='article')
    # ### end Alembic commands ###
