from typing import TYPE_CHECKING, Protocol
from uuid import UUID

from articles.application.dto.article import ArticleDTO, CommentDTO, PaginatedArticleDTO, SpecializationDTO, TagDTO
from common.application.dto import PaginatedDTO
from common.application.query import PaginationParams

if TYPE_CHECKING:
    from articles.application.commands import CreateArticle, CreateComment, EditArticle, EditComment
    from articles.application.queries import GetArticles, GetTagList
    from articles.application.queries.get_specialization import GetSpecializations


class ArticleRepo(Protocol):
    async def create_article(self, article: "CreateArticle") -> None: ...
    async def update_article(self, article: "EditArticle") -> None: ...
    async def delete_article(self, article_id: UUID) -> None: ...
    async def like_article(self, article_id: UUID, user_id: UUID) -> None: ...
    async def dislike_article(self, article_id: UUID, user_id: UUID) -> None: ...
    async def view_article(self, article_id: UUID, user_id: UUID) -> None: ...
    async def cancel_like_article(self, article_id: UUID, user_id: UUID) -> None: ...
    async def cancel_dislike_article(self, article_id: UUID, user_id: UUID) -> None: ...


class ArticleReader(Protocol):
    async def get_article_by_id(self, article_id: UUID) -> ArticleDTO: ...
    async def get_tag_list(self, query: "GetTagList") -> PaginatedDTO[TagDTO]: ...
    async def get_articles(self, query: "GetArticles") -> PaginatedArticleDTO: ...
    async def get_specialization(self, query: "GetSpecializations") -> PaginatedDTO[SpecializationDTO]: ...


class CommentRepo(Protocol):
    async def create_comment(self, comment: "CreateComment") -> None: ...
    async def update_comment(self, comment: "EditComment") -> None: ...
    async def delete_comment(self, comment_id: UUID) -> None: ...
    async def like_comment(self, comment_id: UUID, user_id: UUID) -> None: ...
    async def dislike_comment(self, comment_id: UUID, user_id: UUID) -> None: ...
    async def cancel_like_comment(self, comment_id: UUID, user_id: UUID) -> None: ...
    async def cancel_dislike_comment(self, comment_id: UUID, user_id: UUID) -> None: ...


class CommentReader(Protocol):
    async def get_article_comments(
        self,
        article_id: UUID,
        pagination: PaginationParams,
    ) -> PaginatedDTO[CommentDTO]: ...
    async def get_comment_by_id(self, comment_id: UUID) -> CommentDTO: ...
